### ISSUE TITLE
Commit data to L1

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuel-block-committer#72]
- [x] https://github.com/FuelLabs/fuel-block-committer/issues/50
- [x] https://github.com/FuelLabs/fuel-block-committer/issues/56
- [x] https://github.com/FuelLabs/fuel-block-committer/issues/57
- [x] https://github.com/FuelLabs/fuel-block-committer/issues/79

Nice to have: 
- [ ] https://github.com/FuelLabs/fuel-block-committer/issues/80
- [ ] https://github.com/FuelLabs/fuel-block-committer/issues/58
- [ ] https://github.com/FuelLabs/fuel-block-committer/issues/59

**Comment by digorithm** [comment]
Closing this as most critical sub-tasks have been completed. Nice-to-haves will be implemented on follow-up works.
